name = "Turtle's Auxiliar Modpack"
author = "Aturtle6813"
version = "mc26.1-26.1.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7ea0bff70913321d6bf6792da7635cc1685f900d65a5dcccccde0f40522d099"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
